### ISSUE TITLE
Problems with SSLConnection and the FTP classes

### ISSUE THREAD

**Issue by mattias** [touki653/php-ftp-wrapper#11]
The problem is that I get this error when I try to do anything using the SSLConnection except getting the pwd (using ftp_pwd() with the stream works, but it fails with getCwd() since it runs findDirectoryByName() afterwards):

> PHP Fatal error:  Uncaught [Directory Error] Directory / not found
>        thrown in /path/to/project/vendor/touki/ftp/lib/Touki/FTP/Manager/FTPFilesystemManager.php on line 154

If I use Connection and connect to a server without FTP over explicit TLS, things works as it should.

Example code below:

``` php
namespace Example;

use Touki\FTP\Connection\SSLConnection; 
use Touki\FTP\FTPFactory;
use Touki\FTP\FTP;
use Touki\FTP\Model\Directory;
use Touki\FTP\Model\File;

class Example {
  protected $host = 'myhost';
  protected $user = 'myuser';
  protected $pass = 'mypass';
  protected $connection;
  protected $ftp;

  public function __construct()
  {
    $this->connection = new SSLConnection($this->host, $this->user, $this->pass);
    try {
      $this->connection->open();
    } catch (\Exception $e) {
      var_dump($e);
      exit;
    }

    $factory = new FTPFactory();
    $this->ftp = $factory->build($this->connection);
    var_dump(ftp_pwd($this->connection->getStream())); // string(1) "/"
    var_dump($this->ftp->getCwd()); // PHP Fatal error:  Uncaught [Directory Error] Directory / not found
       // thrown in /path/to/project/vendor/touki/ftp/lib/Touki/FTP/Manager/FTPFilesystemManager.php on line 154
  }
}

$example = new Example;
```

I'm curious to know why this fails when using FTP over explicit TLS (SSLConnection) and not while using regular FTP (Connection).
I can connect to the FTP over explicit TLS with filezilla without any issues.

I've tried both the latest stable and dev-master versions of this ftp-library.

As for the ftp server, it runs proftpd and this particular user I connect as is a virtual user chrooted to its home-dir.

Let me know if you need more information.

**Comment by Sufir** [comment]
That's solves the problem:
$wrapper = new FTPWrapper($connection);
$wrapper->pasv(true);

Actually not only for SSL.
