### ISSUE TITLE
Directory / not found

### ISSUE THREAD

**Issue by onema** [touki653/php-ftp-wrapper#12]
The following code

``` php
    $connection = new Connection($host, $username, $password);
    $connection->open();
    $factory = new FTPFactory();
    $client = $factory->build($connection);
    $client = $this->getClient($input);
    $file = $client->findFileByName($filename);  // <== exception
```

Throws the following exception

```
[Touki\FTP\Exception\DirectoryException]  
  Directory / not found  
```

Where the `$filename` is `myFileName.txt` and is located in the root of my FTP server.

should I be doing something different?

**Comment by flackend** [comment]
@Blackskyliner Thank you! I ran into the issue. For me, setting to to `false` did the trick.
