### ISSUE TITLE
Infinite Loop when deleting a directory

### ISSUE THREAD

**Issue by hm122** [touki653/php-ftp-wrapper#16]
$ftp->delete(new Directory('.test')); results in an infinite loop (output when manually aborting request):

[2015-07-19 17:04:35] local.ERROR: [Directory Error] Directory /.test/././././././././././././././. not found

**Comment by touki653** [comment]
I can't reproduce your error.  
Is your directory named `.test` ? What is inside this directory ?

Can you post the configuration you used to instanciate FTP?

**Comment by hm122** [comment]
Thanks for the fast response! The directory is named .time. I create it before downloading files to get the current server time. Before creating it, I would like to delete it. The directory is in the root folder of the ftp account I use. 

Code:

```
$connection = new Connection($this->host, $this->username, $this->password);
$connection->open();
$factory = new FTPFactory();
$ftp = $factory->build($connection);

$timeFile  = $ftp->findDirectoryByName('.time');
$ftp->delete($timeFile);
```

**Comment by touki653** [comment]
Okay, on the first overview it seems that PHP is unable to list dotted directories.
```php
<?php
$wrapper->rawlist('/');
$wrapper->nlist('/');
```
Do not list files and directories prefixed with a dot. So, the manager is unable to find any directory named that way.

However, the value returned by `findDirectoryByName` should be NULL, and you would have a PHP error when calling to `FTP::delete`, which you don't.

What PHP version are you using? Can you post the dump of your `$tmpFile` variable?

**Comment by hm122** [comment]
Thank you really much for your effort! I am developing on ubuntu 14.04 with PHP 5.5.9-1ubuntu4.11.

I made some more tests now, with directory names like '_time' or also 'time'. When I use the FTPWrapper it works perfectly fine. But with the code below it doesn't (The first time it works of course, but as soon as the folder is present it loops).

```
Log::info('find, before delete');
    $timeFile  = $ftp->findDirectoryByName('time');
    Log::info('delete');
    if($timeFile != null) {
      $ftp->delete($timeFile);
    }

    Log::info('create');
    $ftp->create(new Directory('time'));

    Log::info('find, after create');
    $timeFile  = $ftp->findDirectoryByName('time');

```

Log output:

local.INFO: find, before delete  
local.INFO: delete  
local.ERROR: [Directory Error] Directory /time/./././././././././././././././././././././././././././././././././././././. not found


Var dump of findDirectoryByName:

local.INFO: object(Touki\FTP\Model\Directory)#297 (8) {
  ["realpath":protected]=>
  string(5) "/time"
  ["ownerPermissions":protected]=>
  object(Touki\FTP\Model\Permissions)#299 (1) {
    ["flags":protected]=>
    int(7)
  }
  ["groupPermissions":protected]=>
  object(Touki\FTP\Model\Permissions)#300 (1) {
    ["flags":protected]=>
    int(5)
  }
  ["guestPermissions":protected]=>
  object(Touki\FTP\Model\Permissions)#301 (1) {
    ["flags":protected]=>
    int(5)
  }
  ["owner":protected]=>
  string(8) "f00a868a"
  ["group":protected]=>
  string(8) "w0133294"
  ["size":protected]=>
  string(4) "4096"
  ["mtime":protected]=>
  object(DateTime)#298 (3) {
    ["date"]=>
    string(19) "2015-07-19 20:19:00"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(11) "Europe/Rome"
  }
}

**Comment by touki653** [comment]
It seems some servers returns `.` and `..` directories (like yours) which result in that infinite loop.  
I've made a, what seems like, a fix to your current issue.

Could you pull the latest changes (dev-master), test it again and let me know if that worked for you ?

**Comment by hm122** [comment]
Sorry for the late reply! Just seen that I accidently forget to answer! Thanks for the fix, just tested it with the current version and it seems to work now!
