### ISSUE TITLE
Create a new tag to enable installing latest version with bugfixes

### ISSUE THREAD

**Issue by unicoder88** [touki653/php-ftp-wrapper#27]
Hi!

It's been a year since last version bump, do you mind creating a new tag? Or otherwise we have to reference dev-master.

 In particular I need a bugfix with FileSystemFactory which fixed a problem with incorrect date recognizing for some cases.

Thank you :)

**Comment by unicoder88** [comment]
Or don't :)

**Comment by touki653** [comment]
Sorry about that *slight* delay!
I've created version 1.2.1 with the latest changes
